# Generated by Django 4.2.17 on 2024-12-19 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_created_at_menuitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dnbghptqu/image/upload/v1734616582/placeholder_zwevjg.jpg', max_length=255, verbose_name='image'),
        ),
    ]
